config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get    'admin_home' => 'users#admin_home'
  get    'user_home'  => 'users#user_home'
  get    'admin_index' => 'users#admin_index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  get 'books/history/:id' => 'books#history'

  get 'users/history/:id' => 'users#history'
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :checkout_histories
  resources :users
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'users/history/:id' => 'users#history'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  post '/books/:id' => 'books#checkout'

end

app/views/admins/_form.html.erb
<%= form_for(:admin, :url => {:controller => 'admins', :action => 'create'}) do |f| %>
      <% if @admin.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

            <ul>
              <% @admin.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.text_field :password %>
      </div>
      <div class="field">
        <%= f.label :confirm_password %><br>
        <%= f.text_field :password %>
      </div>
<td>Enter A for creating admin</td>     
 <div class="field">
        <%= f.label :pre_configured %><br>
        <%= f.check_box :pre_configured %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Encrypted password</th>
      <th>Salt</th>
      <th>Pre configured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.email %></td>
        <td><%= admin.name %></td>
        <td><%= admin.encrypted_password %></td>
        <td><%= admin.salt %></td>
        <td><%= admin.pre_configured %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @admin.encrypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @admin.salt %>
</p>

<p>
  <strong>Pre configured:</strong>
  <%= @admin.pre_configured %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>