config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get    'admin_home' => 'users#admin_home'
  get    'user_home'  => 'users#user_home'
  get    'admin_index' => 'users#admin_index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  get 'books/history/:id' => 'books#history'

  get 'users/history/:id' => 'users#history'
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :checkout_histories
  resources :users
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'users/history/:id' => 'users#history'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  post '/books/:id' => 'books#checkout'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  EMAIL_FORMAT = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :name, :presence => true, :uniqueness => true, :length => { :in => 2..50 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_FORMAT
  validates :user_type,
  :inclusion  => { :in => [ 'U','A','P' ],
                   :message    => "Members can have user types : U -> Users, A -> Admins, P -> Pre-configured Admin" }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  wrap_parameters :user, include: [:name, :email, :password, :password_confirmation, :user_type]
  # GET /users
  # GET /users.json
  def index
    if check_if_admin
      @users = User.all
    else
      respond_to do |format|
        format.html{redirect_to user_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if check_if_user || check_if_admin
      @users = User.where(id: params[:id])
    else
      respond_to do |format|
        format.html{redirect_to user_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
    # Even users who are not logged in can access the form and hence no authorization
  end

  # GET /users/1/edit
  def edit
    if check_if_user
      if params[:id].to_s != User.find_by_id(session[:current_user_id]).id.to_s
        respond_to do |format|
          format.html{redirect_to user_home_path, notice: "No sufficient permissions to edit other users"}
        end
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    if ['A'].include?(user_params[:user_type])
      if session[:current_user_id].nil?
        redirect_to login_path, notice: "Only logged in admins can add new admins"
      elsif check_if_user
        redirect_to user_home_path, notice: "No sufficient permissions to add admin"
      elsif check_if_admin
        @user = User.new(user_params)
        if @user.save
          #Tell the UserMailer to send a welcome email after save
          UserMailer.welcome_email(@user).deliver_later
          redirect_to admin_home_path, notice: 'Admin was successfully created'
        else
          render :new
        end
      end
    elsif ['P'].include?(user_params[:user_type])
      if session[:current_user_id].nil?
        redirect_to login_path, notice: "Preconfigured admin cannot be created"
      elsif check_if_user
        redirect_to user_home_path, notice: "Preconfigured admin cannot be created"
      elsif check_if_admin
        redirect_to admin_home_path, notice: "Preconfigured admin cannot be created"
      end
    elsif ['U'].include?(user_params[:user_type])
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          #Tell the UserMailer to send a welcome email after save
          UserMailer.welcome_email(@user).deliver_later
          if session[:current_user_id].nil?
            format.html { redirect_to login_path, notice: 'User was successfully created.Login to access the system' }
          else
            format.html {redirect_to :back, notice: 'User was successfully created.Login to access the system' }
          end
        else
          format.html { render :new }
        end
    end
    end
    end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if session[:current_user_id].nil?
      if check_if_admin
      redirect_to login_path, notice: "Only logged in admins can edit admins"
      else
        redirect_to login_path, notice: "Only logged in users can edit users"
      end
    end

    if params[:id].to_s != User.find_by_id(session[:current_user_id]).id.to_s
       if check_if_user
        redirect_to user_home_path,notice: "Users do not have permissions to update other users"
      elsif check_if_admin
        redirect_to admin_home_path,notice: "Admins do not have permissions to update other users"
      end
    end

    if ['A','P'].include?(user_params[:user_type]) && check_if_user
        redirect_to user_home_path, notice: "No sufficient permissions to edit admin"
    elsif  user_params[:user_type] == 'U' && check_if_admin
        redirect_to admin_home_path, notice: "No sufficient permissions to edit users"
    elsif user_params[:user_type] == 'P'
      redirect_to admin_home_path, notice: "Preconfigured admin details cannot be updated"
    else
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  def admin_index
    if check_if_admin
      @users = User.where(user_type: ['A','P'])
    else
      respond_to do |format|
        format.html{redirect_to user_home_path, notice: "Access to requested link is denied" }
      end
    end
  end
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if check_if_admin
      @checkout_histories=CheckoutHistory.find_by_email(@user.email);
      if @checkout_histories.nil?
      @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end

      else
      @checkout_histories=CheckoutHistory.all
      @checkout_histories.each do |checkout_history|
          if @checkout_histories.last == checkout_history

          puts checkout_history.return_timestamp
          puts DateTime.new(9999,12,31).utc
          puts checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00'


          if !(checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00')
          @user.destroy
          respond_to do |format|
            format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
            format.json { head :no_content }
          end
          else
            respond_to do |format|
              format.html { redirect_to users_path, notice: 'User cannot be destroyed as he has a checked out book.' }
              format.json { head :no_content }
            end
          end
      end
      end
    end
    end
    end

  def delete_admin
if check_if_admin
      @user=User.find_by_id(params[:id])
      @checkout_histories=CheckoutHistory.find_by_email(@user.email);
      if @checkout_histories.nil?
      @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_index_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end

      else
      @checkout_histories=CheckoutHistory.all
      @checkout_histories.each do |checkout_history|
          if @checkout_histories.last == checkout_history

          puts checkout_history.return_timestamp
          puts DateTime.new(9999,12,31).utc
          puts checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00'


          if !(checkout_history.return_timestamp=='9999-12-31T00:00:00+00:00')
@user.destroy
          respond_to do |format|
            format.html { redirect_to admin_index_path, notice: 'User was successfully destroyed.' }
            format.json { head :no_content }
          end
          else
            respond_to do |format|
              format.html { redirect_to admin_index_path, notice: 'User cannot be destroyed as he has a checked out book.' }
              format.json { head :no_content }
            end
          end
      end
      end
    end
    end

end

  def history
    @user = User.find(params[:id])
  end

  def admin_home
    if !check_if_user
      @users = User.where(user_type: ['A','P'])
    else
      respond_to do |format|
        format.html{redirect_to user_home_path, notice: "Access to requested link is denied" }
      end
    end
  end

  def user_home
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :password,:password_confirmation, :user_type)
    end

    def check_if_user
      return true if ['U'].include? User.find_by_id(session[:current_user_id]).user_type
    end

    def check_if_admin
      return true if ['A','P'].include? User.find_by_id(session[:current_user_id]).user_type
    end
    def check_if_pre_configured_admin
      return true if User.find_by_id(session[:current_user_id]).user_type == 'P'
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div>
<br>
<br>
<td>Enter A for admin and U for user</td>
<br>
<br>
  <div class="field">
    <%= f.label :user_type %><br>
    <%= f.text_field :user_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/admin_home.html.erb
<%= provide(:title, "Welcome") %>
<h4>My profile</h4>
<%= link_to 'View my profile', user_path(session[:current_user_id]) %><br/>
<%= link_to 'Edit my profile', edit_user_path(session[:current_user_id]) %><br/>
<br/>
<h4>Manage Admins</h4>
<%= link_to 'Add new Admin',   new_user_path %><br/>
<%= link_to 'View list/See details/Delete admins', admin_index_path%><br/>
<br/>
<h4>Manage Library Books</h4>
<%= link_to 'Add new book', new_book_path %><br/>
<%= link_to 'View list of books', books_path %><br/>
<%= link_to 'View book details', books_path %><br/>
<%= link_to 'Edit book details', books_path %><br/>
<%= link_to 'View Checkout History for a book', books_path %><br/>
<%= link_to 'Checkout/Return books', books_path %>
<br/>
<h4>Library Members</h4>
<%= link_to 'View Checkout history for a user', users_path %><br/>
<%= link_to 'Delete a book', books_path %><br/>
<%= link_to 'List all library members', users_path %><br/>
<%= link_to 'Delete a member', users_path %><br/>

app/views/users/admin_index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Users</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>User type</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>

      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user.user_type == "A"%>
          <%if session[:current_user_id]!=user.id%>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy',controller: "users", action: "delete_admin",id: user.id, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
            <%end%>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', admin_home_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%@user=User.find_by_id(session[:current_user_id])%>
<%if(@user.user_type=='A' || @user.user_type=='P')%>
    <%= link_to 'Back', admin_home_path %>
<%elsif (@user.user_type=='U')%>
    <%= link_to 'Back', user_home_path %>
<%end%>

app/views/users/history.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Checkout Histories</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Isbn</th>
    <th>Checkout timestamp</th>
    <th>Return timestamp</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%if @checkout_histories=CheckoutHistory.all%>

      <% @checkout_histories.each do |checkout_history| %>


          <%if checkout_history.email == @user.email%>
              <tr>
                <td><%= checkout_history.email %></td>
                <td><%= checkout_history.ISBN %></td>
                <td><%= checkout_history.checkout_timestamp %></td>
                <td><%= checkout_history.return_timestamp %></td>

              </tr>
          <%end%>
      <% end %>
  <%end%>
  </tbody>
</table>

<br>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>User type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <% if user.user_type == "U"%>
            <%if session[:current_user_id]!=user.id%>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
        <%end%>
        <td><%= link_to "History", controller: "users", action: "history", id: user.id%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>
<%if @user.user_type=='P' || @user.user_type=='A' %>
<%= link_to 'Back', admin_home_path%>
<%end%>
<%if @user.user_type=='U' %>
<%= link_to 'Back', user_home_path%>
<%end%>

app/views/users/user_home.html.erb
<%= provide(:title, "Welcome") %>

<h4>My Profile</h4>
<%= link_to 'View my profile', user_path(session[:current_user_id]) %><br/>
<%= link_to 'Edit my profile', edit_user_path(session[:current_user_id]) %><br/>
<h4>Enlighten me</h4>
<%= link_to 'Search for a  book', books_search_path %><br/>
<%= link_to 'Checkout a book', books_path %><br/>
<%= link_to 'Return a book', books_path %><br/>
<%= link_to 'View list of books', books_path %><br/>
<% @user=User.find_by_id(session[:current_user_id])%>
<% @checkout_history=CheckoutHistory.where(@user.email)%>
<%= link_to 'View my checkout history', checkout_histories_path %>