config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get    'admin_home' => 'users#admin_home'
  get    'user_home'  => 'users#user_home'
  get    'admin_index' => 'users#admin_index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  get 'books/history/:id' => 'books#history'

  get 'users/history/:id' => 'users#history'
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :checkout_histories
  resources :users
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'users/history/:id' => 'users#history'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  post '/books/:id' => 'books#checkout'

end

app/models/checkout_history.rb
class CheckoutHistory < ActiveRecord::Base

end

app/controllers/checkout_histories_controller.rb
class CheckoutHistoriesController < ApplicationController
  before_action :set_checkout_history, only: [:show, :edit, :update, :destroy]

  # GET /checkout_histories
  # GET /checkout_histories.json
  def index
    @checkout_histories = CheckoutHistory.all
  end

  # GET /checkout_histories/1
  # GET /checkout_histories/1.json
  def show


  end

  # GET /checkout_histories/new
  def new
    @checkout_history = CheckoutHistory.new
  end

  # GET /checkout_histories/1/edit
  def edit
  end

  # POST /checkout_histories
  # POST /checkout_histories.json
  def create
    @checkout_history = CheckoutHistory.new(checkout_history_params)

    respond_to do |format|
      if @checkout_history.save
        format.html { redirect_to @checkout_history, notice: 'Checkout history was successfully created.' }
        format.json { render :show, status: :created, location: @checkout_history }
      else
        format.html { render :new }
        format.json { render json: @checkout_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checkout_histories/1
  # PATCH/PUT /checkout_histories/1.json
  def update
    respond_to do |format|
      if @checkout_history.update(checkout_history_params)
        format.html { redirect_to @checkout_history, notice: 'Checkout history was successfully updated.' }
        format.json { render :show, status: :ok, location: @checkout_history }
      else
        format.html { render :edit }
        format.json { render json: @checkout_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkout_histories/1
  # DELETE /checkout_histories/1.json
  def destroy
    @checkout_history.destroy
    respond_to do |format|
      format.html { redirect_to checkout_histories_url, notice: 'Checkout history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book_history

    @checkout_histories = CheckoutHistory.find_by_id(params[:id])
  end
  helper_method :book_history

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checkout_history
      @checkout_history = CheckoutHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checkout_history_params
      params.require(:checkout_history).permit(:email, :ISBN, :checkout_timestamp, :return_timestamp)
    end
end

app/helpers/checkout_histories_helper.rb
module CheckoutHistoriesHelper
end

app/views/checkout_histories/_form.html.erb
<%= form_for(@checkout_history) do |f| %>
  <% if @checkout_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkout_history.errors.count, "error") %> prohibited this checkout_history from being saved:</h2>

      <ul>
      <% @checkout_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :ISBN %><br>
    <%= f.text_field :ISBN %>
  </div>
  <div class="field">
    <%= f.label :checkout_timestamp %><br>
    <%= f.text_field :checkout_timestamp %>
  </div>
  <div class="field">
    <%= f.label :return_timestamp %><br>
    <%= f.text_field :return_timestamp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkout_histories/edit.html.erb
<h1>Editing Checkout History</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkout_history %> |
<%= link_to 'Back', checkout_histories_path %>

app/views/checkout_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Checkout Histories</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Isbn</th>
      <th>Title</th>
      <th>Checkout timestamp</th>
      <th>Return timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%@user=User.find_by_id(session[:current_user_id])%>
  <tbody>
    <% @checkout_histories.each do |checkout_history| %>
      <tr>

        <%if(checkout_history.email==@user.email || @user.user_type=='A' || @user.user_type=='P')%>
        <td><%= checkout_history.email %></td>
        <td><%= checkout_history.ISBN %></td>
            <%@book=Book.find_by_ISBN(checkout_history.ISBN)%>
            <td><%= @book.title %></td>
        <td><%= checkout_history.checkout_timestamp %></td>
        <td><%= checkout_history.return_timestamp %></td>
        <td><%= link_to 'Show', checkout_history %></td>
        <%end%>

        <%if(@user.user_type=='A' || @user.user_type=='P')%>
            <td><%= link_to 'Edit', edit_checkout_history_path(checkout_history) %></td>
            <td><%= link_to 'Destroy', checkout_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if(@user.user_type=='A' || @user.user_type=='P')%>
<%= link_to 'New Checkout history', new_checkout_history_path %>
<%end%>

app/views/checkout_histories/new.html.erb
<!--<p id="notice"><%= notice %></p>-->
<h1>New Checkout History</h1>

<%= render 'form' %>

<%= link_to 'Back', checkout_histories_path %>

app/views/checkout_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @checkout_history.email %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @checkout_history.ISBN %>
</p>

<p>
  <strong>Checkout timestamp:</strong>
  <%= @checkout_history.checkout_timestamp %>
</p>

<p>
  <strong>Return timestamp:</strong>
  <%= @checkout_history.return_timestamp %>
</p>


<%= link_to 'Back', admin_home_path %>