config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get    'admin_home' => 'users#admin_home'
  get    'user_home'  => 'users#user_home'
  get    'admin_index' => 'users#admin_index'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  get 'books/history/:id' => 'books#history'

  get 'users/history/:id' => 'users#history'
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :checkout_histories
  resources :users
  get 'users/delete_admin/:id' => 'users#delete_admin'

  resources :books
  get 'books/history/:id' => 'books#history'
  get 'users/history/:id' => 'users#history'

  get 'books/search/' => 'books#search'
  post 'books/search_display/' => 'books#search_display'

  post '/books/:id' => 'books#checkout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibSys</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="container">

  <% if !current_page?(login_path) && !session[:current_user_id].nil? %>
      <% if ['A','P'].include?(User.find_by_id(session[:current_user_id]).user_type) %>
          <%= link_to 'Home', admin_home_path %>
      <% else %>
          <%= link_to 'Home', user_home_path %>
      <%end%>
      <%= link_to 'Signout', logout_path %>
  <%end%>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>



</body>

</html>